language: nix

os:
 - osx
 - linux
 
sudo: yes

cache:
  directories:
  - $HOME/nix.store
before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

before_install:
   - travis_retry nix-channel --update
  
install:
   - nix-env -iA nixpkgs.emacs
   - mkdir -p ~/.emacs.d && curl -sSL https://raw.githubusercontent.com/hniksic/emacs-htmlize/master/htmlize.el --output ~/.emacs.d/htmlize.el

script:
  - emacs=$(nix-build default.nix) && echo Produced $emacs

after_success:
  - git tag "${TRAVIS_BUILD_NUMBER}" -m "🚀️ ship it" && git push origin "${TRAVIS_BUILD_NUMBER}"
  - cd docs && emacs -Q index.org --batch --eval "(progn (load \"~/.emacs.d/htmlize.el\")(org-babel-tangle)(org-html-export-to-html))" --kill
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  target-branch: gh-pages
  fqdn: endboxes.codearsonist.com
  on:
    branch: master
